name: dart_depcheck
description: A custom depcheck command for Flutter/Dart projects to check for unused dependencies.
version: 0.0.1-dev.2

repository: https://github.com/cgutierr-zgz/dart_depcheck
homepage: https://github.com/cgutierr-zgz/dart_depcheck
issue_tracker: https://github.com/cgutierr-zgz/dart_depcheck/issues
documentation: https://pub.dev/documentation/dart_depcheck/latest/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.3.0
  path: ^1.8.3
  yaml: ^3.0.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3

executables:
  dart_depcheck:
