name: dart_depcheck
description: A custom depcheck command for Flutter/Dart projects to check for unused dependencies.
version: 1.0.0

repository: https://github.com/cgutierr-zgz/dart_depcheck
homepage: https://github.com/cgutierr-zgz/dart_depcheck
issue_tracker: https://github.com/cgutierr-zgz/dart_depcheck/issues
documentation: https://pub.dev/documentation/dart_depcheck/latest/

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  args: ^2.4.2
  path: ^1.9.0
  pubspec_parse: ^1.3.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ">=3.0.0"
  test: ^1.25.2

executables:
  dart_depcheck:
